### ISSUE TITLE
Trying to import fonts from css causes extension installation to break

### ISSUE THREAD

**Issue by timkpaine** [jupyterlab/theme-cookiecutter#20]
If you try to import a font, say with 
```css
 @font-face {
    font-family: 'Whatever';
    src: url('fonts/Whatever.ttf') format('truetype');
    font-weight: 400;
    font-style: normal;
}
```

Then building jupyterlab with the extension will fail with error:

```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
Error: Automatic publicPath is not supported in this browser
```

**Comment by bollwyvl** [comment]
Gah, fonts! Ever the bane. Thanks for reporting this!

I found a slightly-lighter-weight workaround, inspired by the linked issues, using `base64-inline-loader`:

```bash
jlpm add --dev base64-inline-loader
```

And then:
```css
 @font-face {
    font-family: 'Whatever';
    src: url('!!base64-inline-loader!./fonts/Whatever.ttf') format('truetype');
    font-weight: 400;
    font-style: normal;
}
```

Seems to do the trick!
